name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build "APIClient" --configuration Release
    - name: Test
      run: dotnet test --no-build "ApiUnit.Test" --verbosity normal
    - name: Publish
      run: dotnet publish  "APIClient" -c Release -o Api
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./APIClient/* C:/inetpub/wwwroot/apiasigbcp -Recurse -Force
        iisreset /star
