name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build "APIClient" --configuration Release
    - name: Test
      run: dotnet test --no-build "ApiUnit.Test" --verbosity normal
    - name: Publish
      run: dotnet publish "APIClient" -c Release -o APIClient
    - name: Deploy
      if: ${{ env.RELEASE_VERSION == 'v1' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       BRANCH: gh-pages # The branch the action should deploy to.
       FOLDER: dist # The folder the action should deploy.
       CLEAN: true # Automatically remove deleted files from the deploy branch

   
        
