name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build "APIClient" --configuration Release
    - name: Publish
      run: dotnet publish "C:/inetpub/wwwroot/apiasignacion" -c Release -o APIClient
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "C:/inetpub/wwwroot/apiasignacion" 
    - name: Curl the website as a smoke test
      run: curl http://localhost:9097/apiasignacion
      
    - name: Test
      run: dotnet test --no-build "ApiUnit.Test" --verbosity normal
   
        
